### ISSUE TITLE
Create depolyed site

### ISSUE THREAD

**Issue by stopdaydreaming** [AndreDiop/Collaborative-project#29]
*** USER STORY ***
As a user, I want to see the app deployed to Github pages, so that I can view the app from a url.

*** ACCEPTANCE CRITERIA ***
GIVEN: When I go to a url
WHEN: when the page loads
THEN: I want to see a deployed app that follows UI standards
AND THEN: There are no errors in the console

**Comment by AndreDiop** [comment]
The site is now live below

[**Link to Deployed Site** ](https://andrediop.github.io/Collaborative-project/.)
